%% Types
type(bulbasaur,grass).
type(bulbasaur,poison).
type(ivysaur,grass).
type(ivysaur,poison).
type(venusaur,grass).
type(venusaur,poison).
type(charmander,fire).
type(charmeleon,fire).
type(charizard,fire).
type(charizard,flying).
type(squirtle,water).
type(wartortle,water).
type(blastoise,water).
type(caterpie,bug).
type(metapod,bug).
type(butterfree,bug).
type(butterfree,flying).
type(weedle,bug).
type(weedle,poison).
type(kakuna,bug).
type(kakuna,poison).
type(beedrill,bug).
type(beedrill,poison).
type(pidgey,normal).
type(pidgey,flying).
type(pidgeotto,normal).
type(pidgeotto,flying).
type(pidgeot,normal).
type(pidgeot,flying).
type(rattata,normal).
type(raticate,normal).
type(spearow,normal).
type(spearow,flying).
type(fearow,normal).
type(fearow,flying).
type(ekans,poison).
type(arbok,poison).
type(pikachu,eletric).
type(raichu,eletric).
type(sandshrew,ground).
type(sandslash,ground).
type(nidoran_f,poison).
type(nidorina,poison).
type(nidoqueen,poison).
type(nidoqueen,ground).
type(nidoran_m,poison).
type(nidorino,poison).
type(nidoking,poison).
type(nidoking,ground).
type(clefairy,fairy).
type(clefable,fairy).
type(vulpix,fire).
type(ninetales,fire).
type(jigglypuff,normal).
type(jigglypuff,fairy).
type(wigglytuff,normal).
type(wigglytuff,fairy).
type(zubat,poison).
type(zubat,flying).
type(golbat,poison).
type(golbat,flying).
type(oddish,grass).
type(oddish,poison).
type(gloom,grass).
type(gloom,poison).
type(vileplume,grass).
type(vileplume,poison).
type(paras,bug).
type(paras,grass).
type(parasect,bug).
type(parasect,grass).
type(venonat,bug).
type(venonat,poison).
type(venomoth,bug).
type(venomoth,poison).
type(diglett,ground).
type(dugtrio,ground).
type(meowth,normal).
type(persian,normal).
type(psyduck,water).
type(golduck,water).
type(mankey,fighting).
type(primeape,fighting).
type(growlithe,fire).
type(arcanine,fire).
type(poliwag,water).
type(poliwhirl,water).
type(poliwrath,water).
type(poliwrath,fighting).
type(abra,psychic).
type(kadabra,psychic).
type(alakazam,psychic).
type(machop,fighting).
type(machoke,fighting).
type(machamp,fighting).
type(bellsprout,grass).
type(bellsprout,poison).
type(weepinbell,grass).
type(weepinbell,poison).
type(victreebel,grass).
type(victreebel,poison).
type(tentacool,water).
type(tentacool,poison).
type(tentacruel,water).
type(tentacruel,poison).
type(geodude,rock).
type(geodude,ground).
type(graveler,rock).
type(graveler,ground).
type(golem,rock).
type(golem,ground).
type(ponyta,fire).
type(rapidash,fire).
type(slowpoke,water).
type(slowpoke,psychic).
type(slowbro,water).
type(slowbro,psychic).
type(magnemite,eletric).
type(magnemite,steel).
type(magneton,eletric).
type(magneton,steel).
type(farfetch,normal).
type(farfetch,flying).
type(doduo,normal).
type(doduo,flying).
type(dodrio,normal).
type(dodrio,flying).
type(seel,water).
type(dewgong,water).
type(dewgong,ice).
type(grimer,poison).
type(muk,poison).
type(shellder,water).
type(cloyster,water).
type(cloyster,ice).
type(gastly,ghost).
type(gastly,poison).
type(haunter,ghost).
type(haunter,poison).
type(gengar,ghost).
type(gengar,poison).
type(onix,rock).
type(onix,ground).
type(drowzee,psychic).
type(hypno,psychic).
type(krabby,water).
type(kingler,water).
type(voltorb,eletric).
type(electrode,eletric).
type(exeggcute,grass).
type(exeggcute,psychic).
type(exeggutor,grass).
type(exeggutor,psychic).
type(cubone,ground).
type(cubone,ground).
type(hitmonlee,fighting).
type(hitmonchan,fighting).
type(lickitung,normal).
type(koffing,poison).
type(weezing,poison).
type(rhyhorn,ground).
type(rhyhorn,rock).
type(rhydon,ground).
type(rhydon,rock).
type(chansey,normal).
type(tangela,grass).
type(kangaskhan,normal).
type(horsea,water).
type(seadra,water).
type(goldeen,water).
type(seaking,water).
type(staryu,water).
type(starmie,water).
type(starmie,psychic).
type(mrmime,psychic).
type(mrmime,fairy).
type(scyther,bug).
type(scyther,flying).
type(jynx,ice).
type(jynx,psychic).
type(electabuzz,eletric).
type(magmar,fire).
type(pinsir,bug).
type(tauros,normal).
type(magikarp,water).
type(gyarados,water).
type(gyarados,flying).
type(lapras,water).
type(lapras,ice).
type(ditto,normal).
type(eevee,normal).
type(vaporeon,water).
type(jolteon,eletric).
type(flareon,fire).
type(porygon,normal).
type(omanyte,rock).
type(omanyte,water).
type(omastar,rock).
type(omastar,water).
type(kabuto,rock).
type(kabuto,water).
type(kabutops,rock).
type(kabutops,water).
type(aerodactyl,rock).
type(aerodactyl,flying).
type(snorlax,normal).
type(articuno,ice).
type(articuno,flying).
type(zapdos,eletric).
type(zapdos,flying).
type(moltres,fire).
type(moltres,flying).
type(dratini,dragon).
type(dragonair,dragon).
type(dragonite,dragon).
type(dragonite,flying).
type(mewtwo,psychic).
type(mew,psychic).
%% Pokemons

pokemon('Bulbasaur').
pokemon('Ivysaur').
pokemon('Venusaur').
pokemon('Charmander').
pokemon('Charmeleon').
pokemon('Charizard').
pokemon('Squirtle').
pokemon('Wartortle').
pokemon('Blastoise').
pokemon('Caterpie').
pokemon('Metapod').
pokemon('Butterfree').
pokemon('Weedle').
pokemon('Kakuna').
pokemon('Beedrill').
pokemon('Pidgey').
pokemon('Pidgeotto').
pokemon('Pidgeot').
pokemon('Rattata').
pokemon('Raticate').
pokemon('Spearow').
pokemon('Fearow').
pokemon('Ekans').
pokemon('Arbok').
pokemon('Pikachu').
pokemon('Raichu').
pokemon('Sandshrew').
pokemon('Nidoran_f').
pokemon('Nidorina').
pokemon('Nidoqueen').
pokemon('Nidoran_m').
pokemon('Nidorino').
pokemon('Nidoking').
pokemon('Clefairy').
pokemon('Clefable').
pokemon('Vulpix').
pokemon('Ninetales').
pokemon('Jigglypuff').
pokemon('Wigglytuff').
pokemon('Zubat').
pokemon('Golbat').
pokemon('Oddish').
pokemon('Gloom').
pokemon('Vileplume').
pokemon('Paras').
pokemon('Parasect').
pokemon('Venonat').
pokemon('Venomoth').
pokemon('Diglett').
pokemon('Dugtrio').
pokemon('Meowth').
pokemon('Persian').
pokemon('Psyduck').
pokemon('Golduck').
pokemon('Mankey').
pokemon('Primeape').
pokemon('Growlithe').
pokemon('Arcanine').
pokemon('Poliwag').
pokemon('Poliwhirl').
pokemon('Poliwrath').
pokemon('Abra').
pokemon('Kadabra').
pokemon('Alakazam').
pokemon('Machop').
pokemon('Machoke').
pokemon('Machamp').
pokemon('Bellsprout').
pokemon('Weepinbell').
pokemon('Victreebel').
pokemon('Tentacool').
pokemon('Tentacruel').
pokemon('Geodude').
pokemon('Graveler').
pokemon('Golem').
pokemon('Ponyta').
pokemon('Rapidash').
pokemon('Slowpoke').
pokemon('Slowbro').
pokemon('Magnemite').
pokemon('Magneton').
pokemon('Farfetch').
pokemon('Doduo').
pokemon('Dodrio').
pokemon('Seel').
pokemon('Dewgong').
pokemon('Dewgong').
pokemon('Grimer').
pokemon('Muk').
pokemon('Shellder').
pokemon('Cloyster').
pokemon('Gastly').
pokemon('Haunter').
pokemon('Gengar').
pokemon('Onix').
pokemon('Drowzee').
pokemon('Hypno').
pokemon('Krabby').
pokemon('Kingler').
pokemon('Voltorb').
pokemon('Electrode').
pokemon('Exeggcute').
pokemon('Exeggutor').
pokemon('Cubone').
pokemon('Hitmonlee').
pokemon('Hitmonchan').
pokemon('Lickitung').
pokemon('Koffing').
pokemon('Weezing').
pokemon('Rhyhorn').
pokemon('Rhydon').
pokemon('Chansey').
pokemon('Tangela').
pokemon('Kangaskhan').
pokemon('Horsea').
pokemon('Seadra').
pokemon('Goldeen').
pokemon('Seaking').
pokemon('Staryu').
pokemon('Starmie').
pokemon('MrMime').
pokemon('Scyther').
pokemon('Jynx').
pokemon('Electabuzz').
pokemon('Magmar').
pokemon('Pinsir').
pokemon('Tauros').
pokemon('Magikarp').
pokemon('Gyarados').
pokemon('Lapras').
pokemon('Ditto').
pokemon('Eevee').
pokemon('Vaporeon').
pokemon('Jolteon').
pokemon('Flareon').
pokemon('Porygon').
pokemon('Omanyte').
pokemon('Omanyte').
pokemon('Omastar').
pokemon('Kabuto').
pokemon('Kabutops').
pokemon('Aerodactyl').
pokemon('Snorlax').
pokemon('Articuno').
pokemon('Zapdos').
pokemon('Moltres').
pokemon('Dratini').
pokemon('Dragonair').
pokemon('Dragonite').
pokemon('Mewtwo').
pokemon('Mew').

grass('Bulbasaur').
poison('Bulbasaur').
grass('Ivysaur').
poison('Ivysaur').
grass('Venusaur').
poison('Venusaur').
fire('Charmander').
fire('Charmeleon').
fire('Charizard').
flying('Charizard').
water('Squirtle').
water('Wartortle').
water('Blastoise').
bug('Caterpie').
bug('Metapod').
bug('Butterfree').
flying('Butterfree')
bug('Weedle').
poison('Weedle').
bug('Kakuna').
poison('Kakuna').
bug('Beedrill').
poison('Beedrill').
normal('Pidgey').
flying('Pidgey').
normal('Pidgeotto').
flying('Pidgeotto').
normal('Pidgeot').
flying('Pidgeot').
normal('Rattata').
normal('Raticate').
normal('Spearow').
flying('Spearow').
normal('Fearow').
flying('Fearow').
poison('Ekans').
poison('Arbok').
eletric('Pikachu').
eletric('Raichu').
ground('Sandshrew').
ground('Sandslash').
poison('Nidoran_f').
poison('Nidorina').
poison('Nidoqueen').
ground('Nidoqueen').
poison('Nidoran_m').
poison('Nidorino').
poison('Nidoking').
ground('Nidoking').
fairy('Clefairy').
fairy('Clefable').
fire('Vulpix').
fire('Ninetales').
normal('Jigglypuff').
fairy('Jigglypuff').
normal('Wigglytuff').
fairy('Wigglytuff').
poison('Zubat').
flying('Zubat').
poison('Golbat').
flying('Golbat').
grass('Oddish').
poison('Oddish').
grass('Gloom').
poison('Gloom').
grass('Vileplume').
poison('Vileplume').
bug('Paras').
grass('Paras').
bug('Parasect').
grass('Parasect').
bug('Venonat').
poison('Venonat').
bug('Venomoth').
poison('Venomoth').
ground('Diglett').
ground('Dugtrio').
normal('Meowth').
normal('Persian').
water('Psyduck').
water('Golduck').
fighting('Mankey').
fighting('Primeape').
fire('Growlithe').
fire('Arcanine').
water('Poliwag').
water('Poliwhirl').
water('Poliwrath').
fighting('Poliwrath').
psychic('Abra').
psychic('Kadabra').
psychic('Alakazam').
fighting('Machop').
fighting('Machoke').
fighting('Machamp').
grass('Bellsprout').
poison('Bellsprout').
grass('Weepinbell').
poison('Weepinbell').
grass('Victreebel').
poison('Victreebel').
water('Tentacool').
poison('Tentacool').
water('Tentacruel').
poison('Tentacruel').
rock('Geodude').
ground('Geodude').
rock('Graveler').
ground('Graveler').
rock('Golem').
ground('Golem').
fire('Ponyta').
fire('Rapidash').
water('Slowpoke').
psychic('Slowpoke').
water('Slowbro').
psychic('Slowbro').
eletric('Magnemite').
steel('Magnemite').
eletric('Magneton').
steel('Magneton').
normal('Farfetch').
flying('Farfetch').
normal('Doduo').
flying('Doduo').
normal('Dodrio').
flying('Dodrio').
water('Seel').
water('Dewgong').
ice('Dewgong').
poison('Grimer').
poison('Muk').
water('Shellder').
water('Cloyster').
ice('Cloyster').
ghost('Gastly').
poison('Gastly').
ghost('Haunter').
poison('Haunter').
ghost('Gengar').
poison('Gengar').
rock('Onix').
ground('Onix').
psychic('Drowzee').
psychic('Hypno').
water('Krabby').
water('Kingler').
eletric('Voltorb').
eletric('Electrode').
grass('Exeggcute').
psychic('Exeggcute').
grass('Exeggutor').
psychic('Exeggutor').
ground('Cubone').
ground('Cubone').
fighting('Hitmonlee').
fighting('Hitmonchan').
normal('Lickitung').
poison('Koffing').
poison('Weezing').
ground('Rhyhorn').
rock('Rhyhorn').
ground('Rhydon').
rock('Rhydon').
normal('Chansey').
grass('Tangela').
normal('Kangaskhan').
water('Horsea').
water('Seadra').
water('Goldeen').
water('Seaking').
water('Staryu').
water('Starmie').
psychic('Starmie').
psychic('MrMime').
fairy('MrMime').
bug('Scyther').
flying('Scyther').
ice('Jynx').
psychic('Jynx').
eletric('Electabuzz').
fire('Magmar').
bug('Pinsir').
normal('Tauros').
water('Magikarp').
water('Gyarados').
flying('Gyarados').
water('Lapras').
ice('Lapras').
normal('Ditto').
normal('Eevee').
water('Vaporeon').
eletric('Jolteon').
fire('Flareon').
normal('Porygon').
rock('Omanyte').
water('Omanyte').
rock('Omastar').
water('Omastar').
rock('Kabuto').
water('Kabuto').
rock('Kabutops').
water('Kabutops').
rock('Aerodactyl').
flying('Aerodactyl').
normal('Snorlax').
ice('Articuno').
flying('Articuno').
eletric('Zapdos').
flying('Zapdos').
fire('Moltres').
flying('Moltres').
dragon('Dratini').
dragon('Dragonair').
dragon('Dragonite').
flying('Dragonite').
psychic('Mewtwo').
psychic('Mew').

